'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  en: {
    'nav.logo': 'SKILLS RAG',
    'nav.registry': 'Registry',
    'nav.discover': 'Discover',
    'nav.index': 'Index',
    'nav.settings': 'Settings',
    'nav.detail': 'Skill Detail',
    'nav.login': 'Login',
    'nav.logout': 'Logout',

    'skills.title': 'SKILLS Registry',
    'skills.subtitle':
      'Discover, manage, and utilize specialized AI skills through our semantic vector registry.',
    'skills.search_placeholder': 'Semantic search...',
    'skills.no_found': 'No Skills Found',
    'skills.no_found_desc':
      "We couldn't find any skills matching your search criteria. Try a different query.",
    'skills.view_details': 'View Details',
    'skills.weight': 'Weight',
    'skills.source': 'Source',
    'skills.showing': 'Showing {count} of {total} skills',
    'skills.metrics': 'Metrics',
    'skills.status': 'Status',
    'skills.protocol': 'Protocol',

    'table.identity': 'Skill Identity',
    'table.origin': 'Origin',
    'table.relevance': 'Relevance',
    'table.modified': 'Modified',
    'table.action': 'Action',

    'detail.updated': 'Updated',
    'detail.documentation': 'Documentation',
    'detail.implementation': 'Implementation',
    'detail.copy': 'Copy Code',
    'detail.copied': 'Copied',
    'detail.arguments': 'Arguments',
    'detail.metadata': 'Metadata',
    'detail.owner': 'Owner',
    'detail.contact': 'Contact',
    'detail.path': 'Path',
    'detail.tags': 'Tags',
    'detail.download': 'Download Skill',
    'detail.anonymous': 'Anonymous',
    'detail.not_found': 'Skill Not Found',
    'detail.return': 'Return to Registry',
    'detail.back_home': 'Back to Home',
    'detail.original': 'Original Content',
    'detail.translated': 'Chinese Content',
    'detail.error_loading': 'Failed to load skill details.',
    'detail.error_downloading': 'Failed to download skill.',
    'detail.no_description': 'No description available.',
    'detail.missing_source_title': 'Source Code Missing',
    'detail.missing_source_desc':
      'This skill is registered but the manifest file is missing from local disk. You may need to re-sync the repository to restore it.',
    'detail.repair_sync': 'Repair / Re-sync Source',
    'detail.syncing': 'Syncing...',
    'detail.sync_success': 'Skill synced successfully!',
    'detail.sync_failed': 'Sync failed.',
    'detail.deductions.title': 'Security Deduction Details',
    'detail.deductions.permissions': 'Sensitive permission requests ({count} dangerous perms)',
    'detail.deductions.trust': 'Unverified or non-official source',
    'detail.deductions.ai_risk': 'Dynamic code execution or insecure prompt patterns',
    'detail.deductions.runtime': 'Requires external network connectivity',
    'detail.deductions.metadata': 'Incomplete documentation or metadata',
    'detail.deductions.reputation': 'Low community adoption or verification',
    'detail.deductions.permissions_detail':
      'Detailed analysis: Request for file system read/write, environment variables, and local network discovery.',
    'detail.deductions.trust_detail':
      'Detailed analysis: This skill comes from an unverified third-party repository. Source code origin and author identity are not cryptographically signed.',
    'detail.deductions.ai_risk_detail':
      'Detailed analysis: Pattern detection found dynamic prompt construction with executable segments (Python/JS). High risk of prompt injection or unintended code execution.',
    'detail.deductions.runtime_detail':
      'Detailed analysis: Active socket connections detected. Requires external API access for full functionality, potentially leaking local context.',
    'detail.deductions.metadata_detail':
      'Detailed analysis: Missing docstrings, parameter type definitions, or README.md. High difficulty for human auditing.',
    'detail.deductions.reputation_detail':
      'Detailed analysis: No verified usage metrics or security community endorsements found for this specific identifier.',
    'detail.security_dimension_title': 'Dimension Detail',
    'detail.na': 'N/A',
    'detail.registry': 'Registry',
    'detail.not_found_desc': 'The requested skill could not be found.',
    'detail.audit_v1': 'Security Audit v1.0',
    'detail.heuristic_disclaimer': 'Heuristic assessment - for reference only',
    'detail.evidence': 'Evidence & Location',
    'detail.evidence_snippet': 'Found in implementation snippet',
    'detail.evidence_doc': 'See matching pattern in documentation',
    'detail.high_risk_tooltip': 'High Risk: Dangerous Pattern Detected',
    'detail.light_mode': 'Light Mode',
    'detail.dark_mode': 'Dark Mode',
    'detail.show_evidence': 'Show Evidence & Location',
    'detail.hide_evidence': 'Hide Evidence',
    'detail.evidence_found': 'Security Evidence Found',
    'detail.loading': 'Loading...',
    'detail.use_cases': 'Use Cases',
    'detail.prompt_templates': 'Prompt Templates',
    'detail.faq': 'FAQ',
    'detail.install_guide': 'Install Guide',
    'detail.tabs.docs': 'Documentation',
    'detail.tabs.source': 'Source Explorer',
    'detail.tabs.scenarios': 'Scenarios & Insights',
    'detail.tabs.quality': 'Quality & Security',
    'detail.actions': 'Actions',
    'detail.import': 'Quick Import',
    'detail.quality_score': 'Quality Score',
    'detail.system_status': 'System Status',
    'detail.registry_online': 'Registry Online',
    'detail.index_synced': 'Index Synced',
    'detail.files': 'Files',
    'detail.loading_files': 'Loading Files...',
    'detail.fetching_content': 'Fetching Content...',
    'detail.select_file_desc': 'Select a file to inspect its content',
    'detail.operational_scenarios': 'Operational Scenarios',
    'detail.recommended': 'Recommended',
    'detail.restricted': 'Restricted',
    'detail.total_score': 'Total Score',
    'detail.audit_log': 'Detailed Audit Log',
    'detail.no_quality_data': 'No quality data available for this skill.',
    'detail.view_full_analysis': 'View Full Analysis',
    'detail.using_audit_score_reason':
      'The above scores are derived from the latest security audit result. The detailed heuristic checklist is not available yet.',
    'detail.status': 'Status',
    'detail.repository': 'Repository',
    'detail.active': 'Active',
    'detail.cancel': 'Cancel',
    'detail.translate': 'Translate',
    'detail.quality_assessment': 'Quality Assessment',
    'detail.overall_quality': 'Overall Quality Score',
    'detail.hide_details': 'Hide Details',
    'detail.view_details': 'View Details',
    'detail.quality_checklist': 'Quality Checklist',
    'detail.developer_details': 'Developer Details',
    'detail.hide_files': 'Hide Files',
    'detail.view_files': 'View Files',
    'detail.no_files': 'No files found.',
    'detail.retry': 'Retry',
    'detail.back': 'Back',
    'detail.source_metadata_only':
      'This skill is currently metadata-only. The actual source code is not hosted locally.',
    'detail.error_listing_files': 'Failed to list files.',
    'detail.file_preview': 'File Preview',
    'detail.select_file': 'Select a file to view content',
    'detail.security_report': 'Security Assessment Report',
    'detail.re_audit': 'Re-audit',
    'detail.audit_triggered': 'Audit triggered',
    'detail.audit_failed': 'Audit failed',
    'detail.latest_report': 'Latest Security Report',
    'detail.no_audit_report': 'No audit report available',
    'detail.audit_status': 'Status: {status}',
    'detail.audit_date': 'Audit Date: {date}',
    'detail.translation_failed': 'Translation failed.',
    'detail.translation_enqueued': 'Translation enqueued successfully',
    'detail.download_success': 'Skill downloaded successfully',
    'detail.audit_check_default_title': 'Check Item',
    'detail.audit_risk_unknown': 'Unknown',
    'detail.audit_total_checks': 'Total Checks',
    'detail.audit_high_risk': 'High Risk',
    'detail.audit_medium_risk': 'Medium Risk',
    'detail.audit_low_or_none_risk': 'Low/No Risk',
    'detail.audit_table_item': 'Check Item',
    'detail.audit_table_risk': 'Risk Level',
    'detail.audit_table_impact': 'Score Impact',
    'detail.audit_table_result': 'Finding',
    'detail.audit_table_status': 'Status',
    'detail.audit_finding': 'Finding',
    'detail.audit_detail': 'Details',
    'detail.audit_table_count': '{count} checks visible',
    'detail.audit_sort_risk_on': 'Risk: High → Low',
    'detail.audit_sort_risk_off': 'Sort by Risk',
    'detail.audit_filter_high_on': 'High Risk Only: On',
    'detail.audit_filter_high_off': 'High Risk Only',
    'detail.audit_no_high_risk': 'No high-risk checks found under current filter.',
    'detail.audit_no_extra_details': 'No additional evidence points provided for this check.',
    'translate.modal_title': 'Translate Skill',
    'translate.modal_subtitle': 'Localize content & documentation',
    'translate.target_langs': 'Target Languages',
    'translate.modules': 'Modules to Translate',
    'translate.name': 'Skill Name',
    'translate.description': 'Description',
    'translate.content': 'Documentation (README)',
    'translate.use_cases': 'Use Cases',
    'translate.prompt_templates': 'Prompt Templates',
    'translate.best_practices': 'Best Practices',
    'translate.avoid': 'Avoid Items',
    'translate.faq': 'FAQ',
    'translate.start_btn': 'Start Translation',
    'translate.enqueuing': 'Enqueuing...',
    'translate.translating': 'Translating...',
    'translate.failed': 'Failed',

    'index.title': 'Index Operations',
    'index.subtitle':
      'Monitor the health of the semantic vector index and synchronize external skill repositories.',
    'index.registry_status': 'Registry Status',
    'index.engine_mode': 'Engine Mode',
    'index.rebuild_title': 'Rebuild Index',
    'index.rebuild_desc': 'Perform a complete synchronization of the skill manifest corpus.',
    'index.sync_now': 'Sync Now',
    'index.synchronize': 'Synchronize',
    'index.via_protocol': 'Via Protocol',
    'index.via_source': 'Via Source',
    'index.fetch_repo': 'Fetch Repository',
    'index.official_sync': 'Official Sources Sync',
    'index.sync_all': 'Sync All Official Repos',
    'index.auto': 'Auto',
    'index.english': 'English',
    'index.chinese': 'Chinese',
    'index.sync_engine_output': 'Sync Engine Output',
    'index.initializing': 'Initializing',
    'index.system_monitoring': 'System Monitoring',
    'index.live': 'Live',
    'index.offline': 'Offline',
    'index.ready': 'Ready',
    'index.incomplete': 'Incomplete',
    'index.engine.auto': 'Smart (Auto)',
    'index.engine.sbert': 'Meaning (Semantic)',
    'index.engine.tfidf': 'Keyword (Exact)',
    'index.engine.hybrid': 'Hybrid (Both)',
    'index.engine.sbert': 'SBERT',
    'index.engine.tfidf': 'TF-IDF',
    'index.engine.hybrid': 'Hybrid',
    'index.faiss_index': 'FAISS Index',
    'index.metadata': 'Metadata',
    'index.processing': 'Processing...',
    'index.waiting_for_output': 'Waiting for output...',
    'index.close': 'Close',
    'index.manual_import': 'Manual Import',
    'index.cancel_import': 'Cancel Import',
    'index.github_owner': 'GitHub Owner',
    'index.github_repo': 'GitHub Repo',
    'index.skill_name': 'Skill Name',
    'index.skill_name_zh': 'Skill Name (CN)',
    'index.description': 'Description',
    'index.description_zh': 'Description (CN)',
    'index.tags_placeholder': 'e.g. search, web, utility',
    'index.contact_placeholder': 'e.g. author@example.com',
    'index.skill_path': 'Custom Skill Path (Local)',
    'index.confirm_import': 'Confirm Import & Rebuild Index',
    'index.sync_all_skills_sh': 'Sync Entire Skills.sh Catalog',
    'index.sync_failures': 'Synchronization Failures',
    'index.show_details': 'Show Details',
    'index.hide_details': 'Hide Details',
    'index.upload_zip': 'Upload Archive',
    'index.clear_file': 'Clear File',
    'index.selected_file': 'Selected File',
    'index.drag_drop_zip': 'Drag & Drop ZIP/TAR.GZ or click',
    'index.zip_help':
      'Upload a .zip or .tar.gz archive containing the skill. Manifest fields will be extracted from SKILL.md if available.',
    'index.success_load_skill': 'Skill loaded successfully',
    'index.failed_load_skill': 'Failed to load skill',
    'index.invalid_json': 'Invalid JSON',
    'index.success_update_module': 'Module updated successfully',
    'index.failed_update_module': 'Failed to update module',
    'index.success_enqueue': 'Translation jobs enqueued',
    'index.failed_enqueue': 'Failed to enqueue translation',
    'index.success_rebuild': 'Index rebuild triggered successfully.',
    'index.failed_rebuild': 'Failed to trigger rebuild.',
    'index.success_sync': 'Sync completed successfully.',
    'index.failed_sync': 'Sync failed. Check logs for details.',
    'index.failed_full_sync': 'Failed to trigger full sync.',
    'index.none': 'None',
    'index.internal_mapping': 'Internal Mapping',
    'index.tags_label': 'Tags (comma separated)',
    'index.contact_label': 'Contact/Author',
    'index.not_mapped': 'Not mapped',
    'index.db_version': 'SQLite Database (v2.0)',
    'index.translation_overrides': '翻译与覆盖',
    'index.enter_skill_id': 'Enter Skill ID (e.g. anthropics/skills/web-search)',
    'index.load': 'Load',
    'index.module_override': 'Module Override',
    'index.save_override': 'Save Override',
    'index.translation_jobs': 'Translation Jobs',
    'index.target_languages': 'Target Languages',
    'index.modules_label': 'Modules',
    'index.enqueue_btn': 'Enqueue Translation',
    'index.no_recent_jobs': 'No recent jobs',
    'index.total_skills': 'DB Total:',
    'index.vectorized_skills': 'Vectorized:',
    'index.pending_vectorization': 'Pending:',
    'index.detect_translations': 'Global Detection',
    'index.detecting': 'Detecting...',
    'index.detection_summary':
      'Translation detection complete! Scanned {total} skills, found {enqueued} missing tasks, and added them to the processing queue.',
    'index.detection_success': 'Missing translations enqueued.',
    'index.continue_sync': 'Continue',
    'index.audit_triggered': 'Full security audit triggered',
    'index.failed_audit': 'Failed to trigger security audit',
    'index.audit_pending': 'Audit Pending Skills',

    'discover.title': 'Discover',
    'discover.subtitle':
      "Semantic search powered by AI. Describe what you want to do, and we'll find the matching skills.",
    'discover.engine': 'Engine',
    'discover.matches': 'Matches Found',
    'discover.back': 'Back to Skills',
    'discover.failed': 'Discovery failed. Please try again.',
    'discover.search_placeholder': 'E.g., I want to convert a PDF to text and summarize it...',
    'discover.searching': 'Searching...',
    'discover.find_skills': 'Find Skills',
    'discover.score': 'Score',
    'discover.matched': 'Matched',
    'discover.try_different': 'Try a different description',

    'auth.welcome': 'Welcome Back',
    'auth.registry_access': 'Registry Access v1.0',
    'auth.username': 'Identity / Username',
    'auth.password': 'Security / Password',
    'auth.login_btn': 'Authorize Session',
    'auth.restricted': 'Secure Registry Access - Admin Restricted',
    'auth.failed': 'Login failed. Check your credentials.',

    'pagination.page_of': 'Page {page} of {total}',
    'security.score': 'Security Score',
    'security.audit_v1': 'Security Audit v1.0',
    'security.heuristic_disclaimer': 'Heuristic assessment - score for reference only',
    'security.dimensions.permissions': 'Permissions',
    'security.dimensions.trust': 'Source Trust',
    'security.dimensions.reputation': 'Reputation',
    'security.dimensions.runtime': 'Runtime',
    'security.dimensions.metadata': 'Metadata',
    'security.dimensions.ai_risk': 'AI Risk',
    'security.explainer.title': 'Security Assessment Dimensions',
    'security.explainer.subtitle':
      'We evaluate each AI skill across 6 core dimensions to ensure runtime safety.',
    'security.explainer.disclaimer':
      'Note: This score is auto-generated by a heuristic algorithm. Always audit source code when handling highly sensitive data.',
    'security.risk.dynamic_code':
      'Warning: This skill involves dynamic code execution of model outputs. Run in a sandbox.',
    'security.risk.high_perms':
      'Notice: This skill requests sensitive permissions (Filesystem/Network). Verify necessity.',
    'security.risk.internet':
      'Notice: This skill requires continuous internet connectivity to function.',
    'security.dimensions.architecture': 'Architecture',
    'security.dimensions.maintainability': 'Maintainability',
    'security.dimensions.content': 'Content',
    'security.dimensions.community': 'Community',
    'security.dimensions.security': 'Security',

    'settings.title': 'System Settings',
    'settings.subtitle': 'Manage translation engines, API keys, and system-wide preferences.',
    'settings.translation.title': 'Translation Configuration',
    'settings.translation.desc': 'Configure the engines used for automatic skill localization.',
    'settings.engine.type': 'Engine Type',
    'settings.engine.url': 'Endpoint URL',
    'settings.engine.api_key_header': 'API Key Header',
    'settings.engine.api_key_env': 'API Key / Env Var',
    'settings.engine.api_key_env_placeholder': 'sk-... or ENV_VAR_NAME',
    'settings.security.api_key_placeholder': 'sk-... or ENV_VAR_NAME',
    'settings.engine.test': 'Test Connection',
    'settings.engine.save': 'Save Configuration',
    'settings.engine.add': 'Add Engine',
    'settings.engine.remove': 'Remove',
    'settings.engine.testing': 'Testing...',
    'settings.engine.test_success': 'Connection successful: {result}',
    'settings.engine.test_failed': 'Connection failed: {error}',
    'settings.save_success': 'Settings saved successfully',
    'settings.save_failed': 'Failed to save settings',
    'settings.auth_title': 'Authorization & MCP',
    'settings.auth_subtitle': 'Manage API keys for external agents to access the skills registry.',
    'settings.api_keys': 'API Keys',
    'settings.generate_key': 'Generate New Key',
    'settings.key_name': 'Key Name',
    'settings.expires': 'Expires',
    'settings.last_used': 'Last Used',
    'settings.actions': 'Actions',
    'settings.no_keys': 'No API keys found. Generate one to get started.',
    'settings.mcp_endpoint': 'MCP Endpoint',
    'settings.mcp_help':
      'Use this endpoint and an API key to allow agents like Claude or Cursor to query your skills registry.',
    'settings.copy_key': 'Copy API Key',
    'settings.key_copied': 'API Key copied to clipboard',
    'settings.delete_confirm': 'Are you sure you want to delete this key?',
    'settings.never': 'Never',
    'settings.security_tab': 'Security',
    'settings.translation_tab': 'Translation',
    'settings.authorization_tab': 'Authorization',
    'settings.security.title': 'Security Audit Configuration',
    'settings.security.desc':
      'Configure the LLM provider for semantic security auditing of skills.',
    'settings.security.provider': 'LLM Provider',
    'settings.security.model': 'Model Name',
    'settings.security.api_key': 'API Key',
    'settings.security.base_url': 'Base URL (Optional)',
    'settings.initializing': 'INITIALIZING SYSTEM...',
    'settings.system_online': 'SYSTEM_ONLINE',
    'settings.config_control': '// SYSTEM CONFIGURATION CONTROL',
    'settings.module_id': 'MODULE_{id}',
    'settings.engine.title': 'Translation Engine',
    'settings.engine.active': 'ACTIVE',
    'settings.engine.remove_title': 'Remove Engine',
    'settings.engine.id_prefix': 'ID: ',
    'settings.engine.google_free': 'Google Free (No Key)',
    'settings.engine.bing_free': 'Bing Free (No Key)',

    'dashboard.title': 'Task Progress Dashboard',
    'dashboard.subtitle': 'Real-time monitoring of translation and security audit tasks.',
    'dashboard.translation.title': 'Translation Pipeline',
    'dashboard.security.title': 'Security Audit Pipeline',
    'dashboard.total': 'Total',
    'dashboard.completed': 'Completed',
    'dashboard.processing': 'Processing',
    'dashboard.failed': 'Failed',
    'dashboard.pending': 'Pending',
    'dashboard.queued': 'Queued',
    'dashboard.retry': 'Retry',
    'dashboard.updated_at': 'Last Sync: {time}',
    'dashboard.processes.title': 'Background Processes',
    'dashboard.processes.status': 'Status',
    'dashboard.processes.command': 'Launch Command',
    'dashboard.processes.running': 'Running',
    'dashboard.processes.stopped': 'Stopped',
    'dashboard.processes.copy_command': 'Copy Command',
    'dashboard.processes.start': 'Start',
    'dashboard.processes.stop': 'Stop',
    'dashboard.processes.starting': 'Starting...',
    'dashboard.processes.stopping': 'Stopping...',
    'dashboard.processes.start_success': 'Process {name} started successfully',
    'dashboard.processes.stop_success': 'Process {name} stopped successfully',
    'dashboard.processes.start_failed': 'Failed to start process {name}',
    'dashboard.processes.stop_failed': 'Failed to stop process {name}',
    'dashboard.processes.view_logs': 'View Logs',
    'dashboard.processes.clear_logs': 'Clear Logs',
    'dashboard.processes.clear_success': 'Logs for {name} cleared successfully',
    'dashboard.processes.clear_failed': 'Failed to clear logs for {name}',
    'dashboard.processes.logs_title': 'Process Logs: {name}',
    'dashboard.processes.refresh_logs': 'Refresh',
    'dashboard.processes.no_logs': 'No logs found.',
    'dashboard.last_active': 'Last active',
  },
  zh: {
    'nav.logo': 'SKILLS RAG',
    'nav.registry': '技能注册表',
    'nav.discover': '发现',
    'nav.index': '索引管理',
    'nav.settings': '系统设置',
    'nav.detail': '技能详情',
    'nav.login': '登录',
    'nav.logout': '登出',

    'skills.title': '技能中心',
    'skills.subtitle':
      '通过我们的语义向量注册表发现、管理和利用专业的 AI 技能。专为性能和精度而生。',
    'skills.search_placeholder': '语义搜索...',
    'skills.no_found': '未找到相关技能',
    'skills.no_found_desc': '我们找不到符合您搜索条件的任何技能。请尝试不同的查询。',
    'skills.view_details': '查看详情',
    'skills.weight': '权重',
    'skills.source': '来源',
    'skills.showing': '显示 {total} 个技能中的 {count} 个',
    'skills.metrics': '指标',
    'skills.status': '状态',
    'skills.protocol': '协议',

    'table.identity': '技能标识',
    'table.origin': '来源',
    'table.relevance': '相关度',
    'table.modified': '修改时间',
    'table.action': '操作',

    'detail.updated': '更新于',
    'detail.documentation': '文档说明',
    'detail.implementation': '实现代码',
    'detail.copy': '复制代码',
    'detail.copied': '已复制',
    'detail.arguments': '参数定义',
    'detail.metadata': '元数据',
    'detail.owner': '所有者',
    'detail.contact': '联系方式',
    'detail.path': '本地路径',
    'detail.tags': '标签',
    'detail.download': '下载技能包',
    'detail.anonymous': '匿名',
    'detail.not_found': '未找到该技能',
    'detail.return': '返回列表',
    'detail.back_home': '返回首页',
    'detail.original': '英文原文',
    'detail.translated': '中文内容',
    'detail.error_loading': '加载技能详情失败。',
    'detail.error_downloading': '下载技能失败。',
    'detail.no_description': '暂无描述。',
    'detail.missing_source_title': '源代码缺失',
    'detail.missing_source_desc':
      '该技能已注册，但本地磁盘中缺少清单文件。您可能需要重新同步仓库以恢复它。',
    'detail.repair_sync': '修复 / 重新同步源码',
    'detail.syncing': '正在同步...',
    'detail.sync_success': '技能同步成功！',
    'detail.sync_failed': '同步失败。',
    'detail.deductions.title': '安全扣分明细',
    'detail.deductions.permissions': '请求了敏感权限 ({count} 个危险项)',
    'detail.deductions.trust': '未验证或非官方来源',
    'detail.deductions.ai_risk': '存在动态代码执行或不安全的提示词模式',
    'detail.deductions.runtime': '需要外部网络连接',
    'detail.deductions.metadata': '文档或元数据缺失/不完整',
    'detail.deductions.reputation': '社区采用率或验证度较低',
    'detail.deductions.permissions_detail':
      '详细分析：请求了文件系统读写、环境变量访问以及本地网络发现权限。',
    'detail.deductions.trust_detail':
      '详细分析：该技能来自未验证的第三方仓库。源码来源和作者身份未经过加密签名验证。',
    'detail.deductions.ai_risk_detail':
      '详细分析：检测到动态提示词构建，包含可执行代码段（Python/JS）。存在高风险的提示词注入或意外代码执行风险。',
    'detail.deductions.runtime_detail':
      '详细分析：检测到活跃的 Socket 连接。功能实现依赖外部 API 访问，可能导致本地上下文泄漏。',
    'detail.deductions.metadata_detail':
      '详细分析：缺少文档注释、参数类型定义或 README.md。人工审计难度较高。',
    'detail.deductions.reputation_detail':
      '详细分析：未发现该特定标识符的验证使用指标或安全社区背书。',
    'detail.security_dimension_title': '维度详情',
    'detail.na': '无',
    'detail.registry': '注册表',
    'detail.not_found_desc': '无法找到请求的技能。',
    'detail.audit_v1': '安全审计 v1.0',
    'detail.heuristic_disclaimer': '启发式评估 - 仅供参考',
    'detail.evidence': '证据与位置',
    'detail.evidence_snippet': '在实现代码段中找到',
    'detail.evidence_doc': '在文档中查看匹配模式',
    'detail.high_risk_tooltip': '高风险：检测到危险模式',
    'detail.light_mode': '浅色模式',
    'detail.dark_mode': '深色模式',
    'detail.show_evidence': '显示证据与位置',
    'detail.hide_evidence': '隐藏证据',
    'detail.evidence_found': '检测到安全证据',
    'detail.loading': '加载中...',
    'detail.use_cases': '使用案例',
    'detail.prompt_templates': '提示词模板',
    'detail.faq': '常见问题',
    'detail.install_guide': '安装指南',
    'detail.tabs.docs': '文档说明',
    'detail.tabs.source': '源码预览',
    'detail.tabs.scenarios': '场景与洞察',
    'detail.tabs.quality': '质量与安全',
    'detail.actions': '操作',
    'detail.import': '快速导入',
    'detail.quality_score': '质量评分',
    'detail.system_status': '系统状态',
    'detail.registry_online': '注册表在线',
    'detail.index_synced': '索引已同步',
    'detail.files': '文件列表',
    'detail.loading_files': '正在加载文件...',
    'detail.fetching_content': '正在获取内容...',
    'detail.select_file_desc': '选择一个文件以查看其内容',
    'detail.operational_scenarios': '运营场景',
    'detail.recommended': '推荐',
    'detail.restricted': '受限',
    'detail.total_score': '总评分',
    'detail.audit_log': '详细审计日志',
    'detail.no_quality_data': '该技能暂无质量评估数据。',
    'detail.view_full_analysis': '查看完整分析',
    'detail.using_audit_score_reason': '以上分数基于最近一次安全审计结果，详细启发式检查清单暂未生成。',
    'detail.status': '状态',
    'detail.repository': '代码仓库',
    'detail.active': '激活',
    'detail.cancel': '取消',
    'detail.translate': '翻译',
    'detail.quality_assessment': '质量评估',
    'detail.overall_quality': '整体质量评分',
    'detail.hide_details': '隐藏详情',
    'detail.view_details': '查看详情',
    'detail.quality_checklist': '质量检查清单',
    'detail.developer_details': '开发者详情',
    'detail.hide_files': '隐藏文件',
    'detail.view_files': '查看文件',
    'detail.no_files': '未找到文件。',
    'detail.retry': '重试',
    'detail.back': '返回',
    'detail.source_metadata_only': '该技能目前仅包含元数据。实际源代码未在本地托管。',
    'detail.error_listing_files': '获取文件列表失败。',
    'detail.file_preview': '文件预览',
    'detail.select_file': '选择文件以查看内容',
    'detail.security_report': '安全评估报告',
    'detail.re_audit': '重新审计',
    'detail.audit_triggered': '审计已触发',
    'detail.audit_failed': '审计失败',
    'detail.latest_report': '最新安全审计报告',
    'detail.no_audit_report': '暂无审计报告',
    'detail.audit_status': '状态: {status}',
    'detail.audit_date': '审计时间: {date}',
    'detail.translation_failed': '翻译请求失败。',
    'detail.translation_enqueued': '翻译任务已成功加入队列',
    'detail.download_success': '技能下载成功',
    'detail.audit_check_default_title': '检测项',
    'detail.audit_risk_unknown': '未知',
    'detail.audit_total_checks': '检测总数',
    'detail.audit_high_risk': '高风险',
    'detail.audit_medium_risk': '中风险',
    'detail.audit_low_or_none_risk': '低/无风险',
    'detail.audit_table_item': '检测项',
    'detail.audit_table_risk': '风险等级',
    'detail.audit_table_impact': '分值影响',
    'detail.audit_table_result': '结论摘要',
    'detail.audit_table_status': '状态',
    'detail.audit_finding': '核心结论',
    'detail.audit_detail': '详细说明',
    'detail.audit_table_count': '当前显示 {count} 项',
    'detail.audit_sort_risk_on': '风险排序：高→低',
    'detail.audit_sort_risk_off': '按风险排序',
    'detail.audit_filter_high_on': '仅看高风险：开启',
    'detail.audit_filter_high_off': '仅看高风险',
    'detail.audit_no_high_risk': '当前筛选条件下未发现高风险检测项。',
    'detail.audit_no_extra_details': '该检测项暂无更多补充证据。',
    'translate.modal_title': '翻译技能',
    'translate.modal_subtitle': '本地化内容与文档',
    'translate.target_langs': '目标语言',
    'translate.modules': '待翻译模块',
    'translate.name': '技能名称',
    'translate.description': '技能描述',
    'translate.content': '文档 (README)',
    'translate.use_cases': '使用案例',
    'translate.prompt_templates': '提示词模板',
    'translate.best_practices': '最佳实践',
    'translate.avoid': '避免事项',
    'translate.faq': '常见问题',
    'translate.start_btn': '开始翻译',
    'translate.enqueuing': '正在排队...',
    'translate.translating': '正在翻译...',
    'translate.failed': '失败',

    'index.title': '索引操作',
    'index.subtitle': '监控语义向量索引的健康状态，并同步外部技能库到本地注册表。',
    'index.registry_status': '注册表状态',
    'index.engine_mode': '引擎模式',
    'index.rebuild_title': '重建索引',
    'index.rebuild_desc': '对技能清单语料库执行完整同步，更新所有语义向量。',
    'index.sync_now': '立即同步',
    'index.synchronize': '外部同步',
    'index.via_protocol': '通过协议',
    'index.via_source': '通过源码',
    'index.fetch_repo': '获取仓库',
    'index.official_sync': '官方渠道同步',
    'index.sync_all': '同步所有官方仓库',
    'index.auto': '自动',
    'index.english': '英文',
    'index.chinese': '中文',
    'index.sync_engine_output': '同步引擎输出',
    'index.initializing': '初始化中',
    'index.system_monitoring': '系统监控',
    'index.live': '在线',
    'index.offline': '离线',
    'index.ready': '就绪',
    'index.incomplete': '未完成',
    'index.engine.auto': '智能推荐',
    'index.engine.sbert': '语义搜索 (懂意思)',
    'index.engine.tfidf': '关键词搜索 (对文字)',
    'index.engine.hybrid': '综合搜索 (全都要)',
    'index.engine.sbert': '语义增强',
    'index.engine.tfidf': '关键词匹配',
    'index.engine.hybrid': '混合搜索',
    'index.faiss_index': 'FAISS 索引',
    'index.metadata': '元数据',
    'index.processing': '处理中...',
    'index.waiting_for_output': '等待输出...',
    'index.close': '关闭',
    'index.manual_import': '手动导入',
    'index.cancel_import': '取消导入',
    'index.github_owner': 'GitHub 拥有者',
    'index.github_repo': 'GitHub 仓库',
    'index.skill_name': '技能名称',
    'index.skill_name_zh': '技能名称 (中文)',
    'index.description': '描述',
    'index.description_zh': '描述 (中文)',
    'index.tags_placeholder': '例如：search, web, utility',
    'index.contact_placeholder': '例如：author@example.com',
    'index.skill_path': '自定义技能路径 (本地)',
    'index.confirm_import': '确认导入并重建索引',
    'index.sync_all_skills_sh': '同步整个 Skills.sh 目录',
    'index.sync_failures': '同步失败明细',
    'index.show_details': '查看详情',
    'index.hide_details': '隐藏详情',
    'index.upload_zip': '上传压缩包',
    'index.clear_file': '清除文件',
    'index.selected_file': '已选文件',
    'index.drag_drop_zip': '拖放 ZIP/TAR.GZ 文件或点击选择',
    'index.zip_help': '上传包含技能的 .zip 或 .tar.gz 文件。如有 SKILL.md，将自动提取清单字段。',
    'index.success_load_skill': '技能加载成功',
    'index.failed_load_skill': '加载技能失败',
    'index.invalid_json': 'JSON 格式无效',
    'index.success_update_module': '模块更新成功',
    'index.failed_update_module': '更新模块失败',
    'index.success_enqueue': '翻译任务已加入队列',
    'index.failed_enqueue': '加入翻译队列失败',
    'index.success_rebuild': '索引重建已成功触发。',
    'index.failed_rebuild': '触发重建失败。',
    'index.success_sync': '同步成功完成。',
    'index.failed_sync': '同步失败。请检查日志了解详情。',
    'index.failed_full_sync': '无法触发完整同步。',
    'index.none': '无',
    'index.internal_mapping': '内部映射',
    'index.tags_label': '标签 (逗号分隔)',
    'index.contact_label': '联系人/作者',
    'index.not_mapped': '未映射',
    'index.db_version': 'SQLite 数据库 (v2.0)',
    'index.translation_overrides': '翻译与覆盖',
    'index.enter_skill_id': '输入技能 ID (例如 anthropics/skills/web-search)',
    'index.load': '加载',
    'index.module_override': '模块覆盖',
    'index.save_override': '保存覆盖',
    'index.translation_jobs': '翻译任务',
    'index.target_languages': '目标语言',
    'index.modules_label': '待翻译模块',
    'index.enqueue_btn': '加入翻译队列',
    'index.no_recent_jobs': '暂无最近任务',
    'index.total_skills': '数据库总数:',
    'index.vectorized_skills': '已向量化:',
    'index.pending_vectorization': '待向量化:',
    'index.detect_translations': '全量检测',
    'index.detecting': '正在检测...',
    'index.detection_summary':
      '翻译检测完成！系统已详细扫描了 {total} 个技能，其中发现了 {enqueued} 项缺失的翻译，并已将它们全部加入实时处理队列。',
    'index.detection_success': '检测完成，缺失翻译已加入队列。',
    'index.continue_sync': '继续',
    'index.audit_triggered': '全面安全审计已启动',
    'index.failed_audit': '启动安全审计失败',
    'index.audit_pending': '检测并审计缺失记录的技能',

    'discover.title': '发现',
    'discover.subtitle': '由 AI 驱动的语义搜索。描述你想做什么，我们会找到匹配的技能。',
    'discover.engine': '引擎',
    'discover.matches': '找到匹配项',
    'discover.back': '返回技能列表',
    'discover.failed': '发现失败。请再试一次。',
    'discover.search_placeholder': '例如：我想把 PDF 转成文本并做摘要...',
    'discover.searching': '搜索中...',
    'discover.find_skills': '查找技能',
    'discover.score': '评分',
    'discover.matched': '匹配字段',
    'discover.try_different': '换个描述再试试',

    'auth.welcome': '欢迎回来',
    'auth.registry_access': '注册表访问 v1.0',
    'auth.username': '身份 / 用户名',
    'auth.password': '安全 / 密码',
    'auth.login_btn': '授权会话',
    'auth.restricted': '安全注册表访问 - 仅限管理员',
    'auth.failed': '登录失败。请检查您的凭据。',

    'pagination.page_of': '第 {page} 页，共 {total} 页',
    'security.score': '安全评分',
    'security.audit_v1': '安全评估 v1.0',
    'security.heuristic_disclaimer': '启发式评估 - 分数仅供参考',
    'security.dimensions.permissions': '权限控制',
    'security.dimensions.trust': '来源信任',
    'security.dimensions.reputation': '社区声誉',
    'security.dimensions.runtime': '运行环境',
    'security.dimensions.metadata': '文档完整性',
    'security.dimensions.ai_risk': '交互风险',
    'security.explainer.title': '安全评估维度说明',
    'security.explainer.subtitle':
      '我们通过 6 个核心维度对每个 AI 技能进行启发式评分，以确保运行安全。',
    'security.explainer.disclaimer':
      '注：此评分由启发式算法自动生成，仅供参考。在处理极高敏数据时，请务必人工审计技能源码。',
    'security.risk.dynamic_code': '警告：此技能涉及模型输出的动态代码执行，请在沙箱环境运行。',
    'security.risk.high_perms': '提示：此技能请求了高敏权限（文件系统/网络），请检查其必要性。',
    'security.risk.internet': '提示：此技能需要持续互联网连接以执行。',
    'security.dimensions.architecture': '架构设计',
    'security.dimensions.maintainability': '可维护性',
    'security.dimensions.content': '内容质量',
    'security.dimensions.community': '社区活跃度',
    'security.dimensions.security': '安全合规',

    'settings.title': '系统设置',
    'settings.subtitle': '管理翻译引擎、API 密钥以及系统全局首选项。',
    'settings.translation.title': '翻译配置',
    'settings.translation.desc': '配置用于自动技能本地化的引擎。',
    'settings.engine.type': '引擎类型',
    'settings.engine.url': '接口地址 (URL)',
    'settings.engine.api_key_header': 'API Key 请求头',
    'settings.engine.api_key_env': 'API Key 环境变量',
    'settings.engine.test': '测试连接',
    'settings.engine.save': '保存配置',
    'settings.engine.add': '添加引擎',
    'settings.engine.remove': '移除',
    'settings.engine.testing': '测试中...',
    'settings.engine.test_success': '连接成功：{result}',
    'settings.engine.test_failed': '连接失败：{error}',
    'settings.save_success': '设置保存成功',
    'settings.save_failed': '保存设置失败',
    'settings.auth_title': '授权匹配',
    'settings.auth_subtitle': '管理 API 密钥，让外部 Agent 或编程工具访问技能仓库。',
    'settings.api_keys': 'API 密钥列表',
    'settings.generate_key': '生成新密钥',
    'settings.last_used': '最后使用',
    'settings.actions': '操作',
    'settings.no_keys': '尚未创建 API 密钥。点击上方按钮生成一个。',
    'settings.mcp_endpoint': 'MCP 接口地址',
    'settings.mcp_help': '将此接口地址和 API 密钥配置在 Claude 或 Cursor 中，即可直接检索并使用技能。',
    'settings.copy_key': '复制 API Key',
    'settings.key_copied': 'API Key 已复制到剪贴板',
    'settings.delete_confirm': '确定要删除此密钥吗？',
    'settings.never': '永不过期',
    'settings.security_tab': '安全审计匹配',
    'settings.translation_tab': '翻译配置',
    'settings.authorization_tab': '授权匹配',
    'settings.security.title': '安全审计匹配',
    'settings.security.desc': '配置用于技能语义安全审计的大模型提供商。',
    'settings.security.provider': '大模型提供商',
    'settings.security.model': '模型名称',
    'settings.security.api_key': 'API 密钥',
    'settings.security.base_url': '基础 URL (可选)',
    'settings.initializing': '系统初始化中...',
    'settings.system_online': '系统在线',
    'settings.config_control': '// 系统配置控制',
    'settings.module_id': '模块_{id}',
    'settings.engine.title': '翻译引擎',
    'settings.engine.active': '激活',
    'settings.engine.remove_title': '移除引擎',
    'settings.engine.id_prefix': 'ID: ',
    'settings.engine.google_free': '谷歌免费翻译 (免 Key)',
    'settings.engine.bing_free': '必应免费翻译 (免 Key)',

    'dashboard.title': '任务进度看板',
    'dashboard.subtitle': '实时监控翻译流水线与安全审计任务状态。',
    'dashboard.translation.title': '翻译流水线',
    'dashboard.security.title': '安全审计流水线',
    'dashboard.total': '总数',
    'dashboard.completed': '已完成',
    'dashboard.processing': '处理中',
    'dashboard.failed': '失败',
    'dashboard.pending': '待处理',
    'dashboard.queued': '排队中',
    'dashboard.retry': '重试中',
    'dashboard.updated_at': '最后同步: {time}',
    'dashboard.processes.title': '后台进程监控',
    'dashboard.processes.status': '状态',
    'dashboard.processes.command': '启动命令',
    'dashboard.processes.running': '运行中',
    'dashboard.processes.stopped': '已停止',
    'dashboard.processes.copy_command': '复制命令',
    'dashboard.processes.start': '启动',
    'dashboard.processes.stop': '停止',
    'dashboard.processes.starting': '启动中...',
    'dashboard.processes.stopping': '停止中...',
    'dashboard.processes.start_success': '进程 {name} 启动成功',
    'dashboard.processes.stop_success': '进程 {name} 已停止',
    'dashboard.processes.start_failed': '启动进程 {name} 失败',
    'dashboard.processes.stop_failed': '停止进程 {name} 失败',
    'dashboard.processes.view_logs': '查看日志',
    'dashboard.processes.clear_logs': '清空日志',
    'dashboard.processes.clear_success': '进程 {name} 的日志已清空',
    'dashboard.processes.clear_failed': '清空进程 {name} 的日志失败',
    'dashboard.processes.logs_title': '进程日志: {name}',
    'dashboard.processes.refresh_logs': '刷新',
    'dashboard.processes.no_logs': '暂无日志。',
    'dashboard.last_active': '最后响应',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'en' || saved === 'zh')) {
      setTimeout(() => setLanguageState(saved), 0);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    const langDict =
      (translations as Record<string, Record<string, string>>)[language] ||
      (translations as Record<string, Record<string, string>>)['en'];
    let text = langDict[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
